version: "2"
services:
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
      - scraper:scraper
      - malletservice:malletservice
      - themeservice:themeservice
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.12.1
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  scraper:
    image: mikidi/site-scraping-service
    links:
      - db:database
    environment:
      URL_QUERY: |
          SELECT DISTINCT ?url WHERE {
            GRAPH <http://mu.semte.ch/application> {
              ?event <http://w3id.org/ost/ns#infoUrl> ?url;
                     a <http://w3id.org/ost/ns#Event>.
            }
          }
  malletservice:
    image: mikidi/mallet-topic-tagging-service
    links:
      - db:database
    volumes:
      - /home/michael/Documents/thesis/nl-mallet:/data
  themeservice:
    image: mikidi/mallet-supervised-theming-service
    links:
      - db:database
